name = "hardingspropertyserviceswebsite"
type = "javascript"
account_id = "65107ae3199fd4694b59791603a21660"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-09-10"
main = "./.output/server/index.mjs"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "true"
upload.format = "service-worker"
